<?php

/*
 * Copyright (C) 2015 Anders Lövgren (QNET/BMC CompDept).
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *      http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

namespace SlimBook\Render;

use LogicException;

/**
 * LaTeX output render class.
 *
 * @author Anders Lövgren (Computing Department at BMC, Uppsala University)
 */
class Latex extends FormatterBase
{

        /**
         * Write document content.
         * 
         * @param int $mode The write mode. One or more of the WRITE_XXX constants.
         * @param resource|string $file The output stream or destination file.
         */
        public function write($mode = Formatter::WRITE_ALL, $file = null)
        {
                $this->open($file);

                if ($mode == Formatter::WRITE_ALL) {
                        $this->writeDocument();
                } else {
                        if ($mode & Formatter::WRITE_TITLE) {
                                $this->writeDocTitle();
                        }
                        if ($mode & Formatter::WRITE_TOC) {
                                $this->writePageTOC();
                        }
                        if ($mode & Formatter::WRITE_BODY) {
                                $this->writePageBody();
                        }
                        if ($mode & Formatter::WRITE_FOOTER) {
                                $this->writePageFooter();
                        }
                }

                $this->close();
        }

        /**
         * Write complete LaTeX page.
         */
        private function writeDocument()
        {
                printf("%%\n");
                printf("%% Generated by SlimBook - Simple XML schema for web page markup and type setting of books.\n");
                printf("%% Homepage: http://it.bmc.uu.se/andlov/php/proj/bmc/slimbook\n");
                printf("%%\n");

                printf("\\documentclass{article}\n");
                printf("\\begin{document}\n");
                $this->writeDocTitle();
                $this->writePageTOC();
                printf("\\end{document}\n");
        }

        /**
         * Write document title.
         */
        private function writeDocTitle()
        {
                throw new LogicException("Not yet implemented");
        }

        /**
         * Write table of content (TOC index).
         */
        private function writePageTOC()
        {
                printf("\\tableofcontents\n");
                throw new LogicException("Not yet implemented");
        }

        /**
         * Write main content.
         */
        private function writePageBody()
        {
                throw new LogicException("Not yet implemented");
        }

        /**
         * Write page footer.
         */
        private function writePageFooter()
        {
                throw new LogicException("Not yet implemented");
        }

}
